### ISSUE TITLE
Broken link to Gemma technical report  in `README.md`

### ISSUE THREAD

**Issue by saforem2** [google-deepmind/gemma#1]
The following line provides a broken link to the Gemma technical report in the [`gemma/README.md`](https://github.com/google-deepmind/gemma/blob/main/README.md):

https://github.com/google-deepmind/gemma/blob/036083ab16843e09369a0138630687dba96d4d23/README.md?plain=1#L12

**Comment by emckean** [comment]
This link has been fixed now: https://ai.google.dev/gemma/technical-report

**Comment by saforem2** [comment]
fixed in #2
