### ISSUE TITLE
how can run, input a sentence, return results

### ISSUE THREAD

**Issue by songsh** [google-deepmind/gemma#13]
not found, please give me a way

**Comment by suryabhupa** [comment]
Are you using the colab that we've given here?

**Comment by gustheman** [comment]
this may be able to help: https://ai.google.dev/gemma/docs/jax_inference

**Comment by Gopi-Uppari** [comment]
Hi @songsh,

Could you please confirm if this issue is resolved for you with the above comment ? Please feel free to close the issue if it is resolved ?

Thank you.

**Comment by tilakrayal** [comment]
Closing this issue due to lack of recent activity,  Please feel free reopen if this is still a valid request. Thank you!
