### ISSUE TITLE
How can I set temperatur of model when I reload Keras fine-tuned Gemma?

### ISSUE THREAD

**Issue by XinyueZ** [google-deepmind/gemma#14]

**Comment by suryabhupa** [comment]
Is there a way in the sampler method you use to specify the temperature or sampling method (e.g. nucleus, top-k, etc.)?

**Comment by gustheman** [comment]
you can set the sampler for that, more information at the bottom in this tutorial: https://ai.google.dev/gemma/docs/keras_inference

**Comment by Gopi-Uppari** [comment]
Hi,

Could you please confirm if this issue is resolved for you with the above comment ? Please feel free to close the issue if it is resolved ?

Thank you.

**Comment by XinyueZ** [comment]
Close please

**Comment by tilakrayal** [comment]
As mentioned, Closing this issue,  Please feel free to reopen if this is still a valid request. Thank you!
