### ISSUE TITLE
Issue when "$ pytest ."

### ISSUE THREAD

**Issue by seongho-git** [google-deepmind/gemma#26]
I followed the instructions and I did $ pytest .
--experiment environment--
RTX 4090 Titan, docker image : nvidia/cuda:12.2.2-cudnn8-devel-ubuntu22.04
Here is the result, how can I fix it?

======================================================================== test session starts ========================================================================
platform linux -- Python 3.10.12, pytest-8.1.1, pluggy-1.4.0
rootdir: /workspace/gemma
configfile: pyproject.toml
collected 16 items                                                                                                                                                  

gemma/layers_test.py ...                                                                                                                                      [ 18%]
gemma/modules_test.py ...F.                                                                                                                                   [ 50%]
gemma/positional_embeddings_test.py F.                                                                                                                        [ 62%]
gemma/sampler_test.py ..                                                                                                                                      [ 75%]
gemma/transformer_test.py ....                                                                                                                                [100%]

============================================================================= FAILURES ==============================================================================
_____________________________________________________________________ FeedForwardTest.test_ffw0 _____________________________________________________________________

self = <gemma.modules_test.FeedForwardTest testMethod=test_ffw0>, features = 2, hidden_dim = 3, batch_size = 2, expected_val = [11.72758674, 47.99916]
expected_shape = (2, 1, 2)

    @parameterized.parameters(
        dict(
            features=2,
            hidden_dim=3,
            batch_size=2,
            expected_val=[11.72758674, 47.99916],
            expected_shape=(2, 1, 2),
        ),
    )
    def test_ffw(
        self, features, hidden_dim, batch_size, expected_val, expected_shape
    ):
      inputs = jnp.arange(1, batch_size+1)[:, None, None]
      inputs = jnp.repeat(inputs, features, axis=-1)
      ffw = modules.FeedForward(features=features, hidden_dim=hidden_dim)
      params = {
          'gating_einsum': jnp.ones((2, features, hidden_dim)),
          'linear': jnp.ones((hidden_dim, features)),
      }
    
      outputs = ffw.apply({'params': params}, inputs)
    
>     np.testing.assert_array_almost_equal(outputs[:, 0, 0], expected_val)

gemma/modules_test.py:132: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python3.10/contextlib.py:79: in inner
    return func(*args, **kwds)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

args = (<function assert_array_almost_equal.<locals>.compare at 0x7fabb5e4f250>, Array([11.727587, 47.999153], dtype=float32), [11.72758674, 47.99916])
kwds = {'err_msg': '', 'header': 'Arrays are not almost equal to 6 decimals', 'precision': 6, 'verbose': True}

    @wraps(func)
    def inner(*args, **kwds):
        with self._recreate_cm():
>           return func(*args, **kwds)
E           AssertionError: 
E           Arrays are not almost equal to 6 decimals
E           
E           Mismatched elements: 1 / 2 (50%)
E           Max absolute difference: 6.86279297e-06
E           Max relative difference: 1.42977356e-07
E            x: array([11.727587, 47.999153], dtype=float32)
E            y: array([11.727587, 47.99916 ])

/usr/lib/python3.10/contextlib.py:79: AssertionError
_____________________________________________________ PositionalEmbeddingsTest.test_adds_positional_embeddings0 _____________________________________________________
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

self = <gemma.positional_embeddings_test.PositionalEmbeddingsTest testMethod=test_adds_positional_embeddings0>, input_embedding_shape = (2, 1, 1, 5), position = 3
max_wavelength = 100, expected = [[[[1.1411201, 1.0299965, 0.0100075, 1.99955, 1.0]]], [[[1.1411201, 1.0299965, 0.0100075, 1.99955, 1.0]]]]

    @parameterized.parameters(
        dict(
            input_embedding_shape=(2, 1, 1, 5),
            position=3,
            max_wavelength=100,
            expected=[[[[1.1411201, 1.0299965, 0.0100075, 1.99955, 1.0]]],
                      [[[1.1411201, 1.0299965, 0.0100075, 1.99955, 1.0]]]]
        )
    )
    def test_adds_positional_embeddings(
        self, input_embedding_shape, position, max_wavelength, expected
    ):
>     outputs = positional_embeddings.add_positional_embedding(
          jnp.ones(input_embedding_shape), position, max_wavelength
      )

gemma/positional_embeddings_test.py:38: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
gemma/positional_embeddings.py:42: in add_positional_embedding
    return input_embedding + position_embedding
../gemma-demo/lib/python3.10/site-packages/jax/_src/numpy/array_methods.py:264: in deferring_binary_op
    return binary_op(*args)
../gemma-demo/lib/python3.10/site-packages/jax/_src/numpy/ufuncs.py:99: in fn
    x1, x2 = promote_args(numpy_fn.__name__, x1, x2)
../gemma-demo/lib/python3.10/site-packages/jax/_src/numpy/util.py:381: in promote_args
    return promote_shapes(fun_name, *promote_dtypes(*args))
../gemma-demo/lib/python3.10/site-packages/jax/_src/numpy/util.py:249: in promote_shapes
    _rank_promotion_warning_or_error(fun_name, shapes)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

fun_name = 'add', shapes = [(2, 1, 1, 5), (5,)]

    def _rank_promotion_warning_or_error(fun_name: str, shapes: Sequence[Shape]):
      if config.numpy_rank_promotion.value == "warn":
        msg = ("Following NumPy automatic rank promotion for {} on shapes {}. "
               "Set the jax_numpy_rank_promotion config option to 'allow' to "
               "disable this warning; for more information, see "
               "https://jax.readthedocs.io/en/latest/rank_promotion_warning.html.")
        warnings.warn(msg.format(fun_name, ' '.join(map(str, shapes))))
      elif config.numpy_rank_promotion.value == "raise":
        msg = ("Operands could not be broadcast together for {} on shapes {} "
               "and with the config option jax_numpy_rank_promotion='raise'. "
               "For more information, see "
               "https://jax.readthedocs.io/en/latest/rank_promotion_warning.html.")
>       raise ValueError(msg.format(fun_name, ' '.join(map(str, shapes))))
E       ValueError: Operands could not be broadcast together for add on shapes (2, 1, 1, 5) (5,) and with the config option jax_numpy_rank_promotion='raise'. For more information, see https://jax.readthedocs.io/en/latest/rank_promotion_warning.html.

../gemma-demo/lib/python3.10/site-packages/jax/_src/numpy/util.py:267: ValueError
====================================================================== short test summary info ======================================================================
FAILED gemma/modules_test.py::FeedForwardTest::test_ffw0 - AssertionError: 
FAILED gemma/positional_embeddings_test.py::PositionalEmbeddingsTest::test_adds_positional_embeddings0 - ValueError: Operands could not be broadcast together for add on shapes (2, 1, 1, 5) (5,) and with the config option jax_numpy_rank_promotion='raise'. For more i...
============================================================== 2 failed, 14 passed in 91.04s (0:01:31) ==============================================================

**Comment by canyon289** [comment]
It looks like there is a slight float mismatch on the hardware for some reason but the results are really close. If running the test for verification I suggest loosening the tolerance on the comparison just a bit.

**Comment by seongho-git** [comment]
I agree with your words. If I make a better result with more consideration, I will share it for all. Thank you.
