### ISSUE TITLE
How to set stop words

### ISSUE THREAD

**Issue by XYaoooo** [google-deepmind/gemma#30]
Hi, when I prompt gemma to answer question following format:
Q:####
A:#####

Q:####
A:####

Q:#####
A:

 I have no idea how to stop gemma when generating "Q:".

**Comment by canyon289** [comment]
Subclassing sampler and adding a break there for the tokens you want to stop on would do the trick!

https://github.com/google-deepmind/gemma/blob/main/gemma/sampler.py#L280

**Comment by Gopi-Uppari** [comment]
Hi @XYaoooo,

Could you please confirm if this issue is resolved for you with the above comment ? Please feel free to close the issue if it is resolved ?

Thank you.

**Comment by XYaoooo** [comment]
Thanks for your reply.
