### ISSUE TITLE
Function calling with Gemma

### ISSUE THREAD

**Issue by JKORRA** [google-deepmind/gemma#38]
How can i do function calling using Gemma on local Hardware ?

**Comment by Meshwa428** [comment]
its not available with the model, but you can try to prompt it to return json responses, its good at giving json response. OR may be try to finetune it with LoRA, you can do it even on google colab, or try kaggle (they provide 30hr of free gpu time you can have 2 t4 or 1 p100 gpu. 30hr time refreshes every week)

**Comment by JKORRA** [comment]
Thanks, i will try !

**Comment by Gopi-Uppari** [comment]
Hi @JKORRA,

Could you please confirm if this issue is resolved for you with the above comment ? Please feel free to close the issue if it is resolved ?

Thank you.

**Comment by tilakrayal** [comment]
Closing this issue due to lack of recent activity,  Please feel free reopen if this is still a valid request. Thank you!
