### ISSUE TITLE
Sliding Window Attention

### ISSUE THREAD

**Issue by aniquetahir** [google-deepmind/gemma#40]
I noticed this version does not contain sliding window attention needed for Gemma 2 models.

**Comment by gustheman** [comment]
We are working to release the Gemma 2 related code soon, sorry for the delay

**Comment by Mddct** [comment]
any update?

**Comment by canyon289** [comment]
Hey folks, Thank you for your interest

It will be released soon and contain all the v2 updates such as sliding window attention and GQA. I'll update this issue in the next two weeks!

**Comment by Gopi-Uppari** [comment]
Hi @aniquetahir,

Sliding window attention has been added to the Gemma 2 models. Could you please check it.

Thank you.

**Comment by aniquetahir** [comment]
> Hi @aniquetahir,
> 
> Sliding window attention has been added to the Gemma 2 models. Could you please check it.
> 
> Thank you.

This is great!
