### ISSUE TITLE
pip install fail

### ISSUE THREAD

**Issue by YUHAI0** [google-deepmind/gemma#43]
faile message as below: 

Collecting git+https://github.com/google-deepmind/gemma.git
  Cloning https://github.com/google-deepmind/gemma.git to c:\users\yu.hai2\appdata\local\temp\pip-req-build-7vva4aj3
  Running command git clone --filter=blob:none --quiet https://github.com/google-deepmind/gemma.git 'C:\Users\yu.hai2\AppData\Local\Temp\pip-req-build-7vva4aj3'
  Resolved https://github.com/google-deepmind/gemma.git to commit a0504162f99a1c238efb37b8197e711c0f3808fd
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting absl-py<3.0.0,>=2.1.0 (from gemma==1.0.0)
  Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
Collecting flax>=0.8 (from gemma==1.0.0)
  Using cached flax-0.8.5-py3-none-any.whl.metadata (10 kB)
Collecting sentencepiece<0.2.0,>=0.1.99 (from gemma==1.0.0)
  Using cached sentencepiece-0.1.99.tar.gz (2.6 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\yu.hai2\AppData\Local\Temp\pip-install-_8v8y5vf\sentencepiece_7d45cd2cee0c47fa84b63038a551fc0f\setup.py", line 126, in <module>
          subprocess.check_call([
        File "subprocess.py", line 408, in check_call
        File "subprocess.py", line 389, in call
        File "subprocess.py", line 1026, in __init__
        File "subprocess.py", line 1538, in _execute_child
      FileNotFoundError: [WinError 2] 系统找不到指定的文件。
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by KumarGitesh2024** [comment]
Could you please try again with the  command "!git clone https://github.com/google-deepmind/gemma.git" and let me know if the issue still persists? Thank you

**Comment by Gopi-Uppari** [comment]
Hi @YUHAI0,

Could you please confirm if this issue is resolved for you with the above comment ? Please feel free to close the issue if it is resolved ?

Thank you.

**Comment by tilakrayal** [comment]
Closing this issue due to lack of recent activity,  Please feel free reopen if this is still a valid request. Thank you!
