### ISSUE TITLE
NameError found flax repo due to case sensitivity 

### ISSUE THREAD

**Issue by KumarGitesh2024** [google-deepmind/gemma#45]
when I was executing fine tuning tutorial notebook I found the code error in this notebook : <https://github.com/google-deepmind/gemma/blob/main/colabs/fine_tuning_tutorial.ipynb>

![NameError](https://github.com/user-attachments/assets/e270d553-7ad9-4d09-9eae-88e3c773243f)

And also getting the same error in the below notebooks, could you please recheck it
<https://github.com/google-deepmind/gemma/blob/main/colabs/gsm8k_eval.ipynb>
<https://github.com/google-deepmind/gemma/blob/main/colabs/sampling_tutorial.ipynb>
I am providing a [gist](https://colab.sandbox.google.com/gist/KumarGitesh2024/1f39817c41a9dd2a1d565fd4ce09335d/fine_tuning_under_flax_repo_gemma.ipynb) for reference .

**Comment by Gopi-Uppari** [comment]
Hi @KumarGitesh2024,

I was able to reproduce the issue, and to prevent this error, it's necessary to change the variant to `VARIANT`. Additionally, some users have already raised [pull requests](https://github.com/google-deepmind/gemma/pull/52) to address this problem. Our team will review and provide feedback as soon as possible.

Thank you.

**Comment by Gopi-Uppari** [comment]
Hi @KumarGitesh2024,

Could you please confirm if this issue is resolved for you with the above comment ? Please feel free to close the issue if it is resolved ?

Thank you.

**Comment by tilakrayal** [comment]
Closing this issue as stale. Feel free to re-open if the issue still persists. Thank you!
