### ISSUE TITLE
OOM when running a number of prompts sequentially 

### ISSUE THREAD

**Issue by windmaple** [google-deepmind/gemma#57]
Hi,

I encountered OOM when running a number of prompts sequentially (basically running MMLU subset). Here is the [colab](https://colab.research.google.com/drive/1FnAJpiZPs3RmhdKCwrn_lnj6cAUoI4yQ?usp=sharing) to reproduce. I'm already deleting the sampler and have enabled GC.

**Comment by Gopi-Uppari** [comment]
Hi @windmaple,

I was able to reproduce the OOM error on the 30th prompt out of 103 prompts when running them sequentially. Even after using `del sampler`, the model still consumes significant system RAM for certain prompts, causing the OOM issue.

To address this problem, you can:
1. Execute a batch of prompts, save the results, and then click on **Runtime > Disconnect and delete runtime**. Afterward, select **Runtime > Run all**. Repeat this process for the remaining batches.
  
Alternatively, 
2. Increase your system RAM to more than 15GB to handle the memory requirements better.

Could you please refer to this [gist file](https://colab.research.google.com/gist/Gopi-Uppari/cf253cd79245b18576626e35f90d0c97/gemma_lib_oom.ipynb)

Thank you.

**Comment by windmaple** [comment]
#1 doesn't work because I'm trying to use Eleuther AI eval harness. Resetting the runtime basically restarts everything. And for a full eval of MMLU, I don't know how many manually restarts are needed.

#2, sure. But I think memory management in the lib is not well done.

**Comment by Gopi-Uppari** [comment]
Hi @windmaple,

Regarding point 1, what you mentioned is accurate. Then go ahead with point 2 by increasing the system RAM.

But I think memory management in the lib is not well done. --> we can't say for certain, but this could be one possible reason.

Thank you.

**Comment by Conchylicultor** [comment]
Thanks for reporting. I agree we should improve memory usage. It's something we're currently looking at
